# @package _global_
seed: 42
dataloader:
  batch_size: ${oc.select:dataloader.batch_sizes.${data.name}}
  batch_sizes:
    sepsis: 256
    bpic13: 128
    bpic17: 2048
    bpic19: 2048
  num_workers: 12
training:
  device: cuda:0
wandb:
  project: diffusion-probabilistic-suffix
  mode: online
