# @package _global_
optimizer:
  lr: ${oc.select:training.regimes.${data.name}.lr}
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  warmup_epochs: ${oc.select:training.regimes.${data.name}.warmup_epochs}
  min_lr_factor: 0.1
training:
  max_epochs: ${oc.select:training.regimes.${data.name}.max_epochs}
  val_every_n_epochs: ${oc.select:training.regimes.${data.name}.val_every_n_epochs}
  grad_clip_norm: 1.0
  validation_pairs: ${oc.select:training.regimes.${data.name}.validation_pairs}
  generation_pairs: ${oc.select:training.regimes.${data.name}.generation_pairs}
  regimes:
    sepsis:
      lr: 0.0003
      warmup_epochs: 5
      max_epochs: 200
      val_every_n_epochs: 2
      validation_pairs: 10000
      generation_pairs: 2000
    bpic13:
      lr: 0.0003
      warmup_epochs: 5
      max_epochs: 300
      val_every_n_epochs: 2
      validation_pairs: 10000
      generation_pairs: 1000
    bpic17:
      lr: 0.0006
      warmup_epochs: 5
      max_epochs: 100
      val_every_n_epochs: 1
      validation_pairs: 50000
      generation_pairs: 4096
    bpic19:
      lr: 0.0006
      warmup_epochs: 5
      max_epochs: 100
      val_every_n_epochs: 1
      validation_pairs: 50000
      generation_pairs: 4096
early_stopping:
  patience_epochs: 30
  min_delta_perc: 0.005
inference:
  validation_samples: 32
  evaluation_samples: 100
  generation_rows_upper_bound: 8192
