# @package _global_
optimizer:
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.95
  min_lr_factor: 0.1
training:
  grad_clip_norm: 1.0
early_stopping:
  min_delta_perc: 0.005
inference:
  validation_samples: 32
  evaluation_samples: 100
  generation_rows_upper_bound: 8192
