defaults:
- output/default
- _self_
generations: ???
invocation_id: ${now:%Y%m%d-%H%M%S-%f}
workers: null
hydra:
  run:
    dir: ${source_output:evaluate,generations,${generations},${invocation_id}}
  sweep:
    dir: outputs/evaluate
    subdir: ${source_subdir:evaluate,generations,${generations},${invocation_id}}
