defaults:
- output/default
- _self_
checkpoint: ???
invocation_id: ${now:%Y%m%d-%H%M%S-%f}
device: null
num_samples: null
num_workers: null
hydra:
  run:
    dir: ${source_output:generate,checkpoint,${checkpoint},${invocation_id}}
  sweep:
    dir: outputs/generate
    subdir: ${source_subdir:generate,checkpoint,${checkpoint},${invocation_id}}
