# @package _global_
optimizer:
  lr: 0.0006
  warmup_steps: 1500
training:
  max_steps: 30000
  val_every_n_steps: 300
  validation_pairs: 50000
  generation_pairs: 4096
early_stopping:
  patience_validations: 20
dataloader:
  batch_size: 2048
